### PR TITLE
added jackson-core and jackson-annotations deps

### PR DESCRIPTION
**Pull request by nitinvijay94**
To avoid dependency frustration for others =)

### CODE REVIEW

**Comment by oschwald** [comment]
In what case was this causing problems? They are already transitive dependencies via `jackson-databind`.

**Comment by nitinvijay94** [comment]
@oschwald Hmm, I was error-ing out on Class Not Found exceptions when trying to build my project including only 
`<dependency>
            <groupId>com.maxmind.geoip2</groupId>
            <artifactId>geoip2</artifactId>
            <version>2.10.0</version>
 </dependency>` 
and the solution ended up being specifying those jackson dependencies.

**Comment by oschwald** [comment]
I wonder if there is something else in your project pulling in older versions or something. Here is what I see for in a project using `geoip2` when running `mvn dependency:tree`:

```
[INFO] +- com.maxmind.geoip2:geoip2:jar:2.10.0:compile
[INFO] |  +- com.maxmind.db:maxmind-db:jar:1.2.2:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.9.2:compile
[INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.9.2:compile
```

I'd be curious to see what your `mvn dependency:tree` looks like without these explicit dependencies.

**Comment by nitinvijay94** [comment]
```
(ntropy) NitinsMacBookPro:udfs nitin$ mvn dependency:tree | grep -A 1 -B 1 -E 'maxmind|jackson'
[INFO] +- com.sixsense:libs:jar:0.1:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.4.0:compile
[INFO] |  +- org.jdbi:jdbi:jar:2.53:compile
--
--
[INFO] |  |  +- org.slf4j:slf4j-log4j12:jar:1.7.10:provided
[INFO] |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:provided
[INFO] |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:provided
[INFO] |  |  +- org.apache.avro:avro:jar:1.7.4:provided
--
--
[INFO] |  |     +- com.sun.jersey:jersey-client:jar:1.9:provided
[INFO] |  |     +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.13:provided
[INFO] |  |     \- org.codehaus.jackson:jackson-xc:jar:1.9.13:provided
[INFO] |  +- org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.7.2:provided
--
--
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.1.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.1.1:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.1.1:compile
[INFO] +- mysql:mysql-connector-java:jar:5.1.33:compile
--
--
[INFO] |  +- io.airlift:json:jar:0.147:provided
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.8.1:provided
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.8.1:provided
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.8.1:provided
[INFO] |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.8.1:provided
[INFO] |  +- io.airlift:configuration:jar:0.147:provided
--
--
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.22.2:provided
[INFO] |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.8.1:provided
[INFO] |  +- io.airlift:jmx:jar:0.147:provided
--
--
[INFO] +- joda-time:joda-time:jar:2.8.2:compile
[INFO] +- com.maxmind.geoip2:geoip2:jar:2.10.0:compile
[INFO] |  \- com.maxmind.db:maxmind-db:jar:1.2.2:compile
[INFO] +- junit:junit:jar:4.11:test
```
Ah, looks like there is an older version.
Although, if it's such a common library, might be worth specifying the correct versions anyway to avoid confusion.

**Comment by oschwald** [comment]
Thanks for checking and for the PR! Given how Maven's dependency resolution works, I think you make a good point as depending on it directly is more likely to override dependencies by other packages. Unfortunately, it still won't guarantee that the correct version is pulled in.

**Pull request merged**
